name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build and Deploy to GitHub Pages
      run: |
        npm run build
        echo "chamodmalintha.github.io/react-custom-hook" > build/CNAME

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: master
        FOLDER: build